### ISSUE TITLE
Colon-delimited :standard_emoji: aren't properly converted to graphical emoji in transcript

### ISSUE THREAD

**Issue by oneup40** [mahtoid/DiscordChatExporterPy#20]
When I send a colon-delimited standard emoji, such as `:thumbsup`, in a message using discord.py, the Discord web client renders the emoji as the actual graphical representation 👍. The exported transcript still renders it as the `:thumbsup:` text though, instead of the graphic. Note that this only happens when a colon-delimited emoji is sent directly with discord.py (and probably other libraries), but not when sent from the standard web client. (I suspect the web client might be pre-processing the message to replace the emoji on the client side before it's sent, but I don't have anything to back that up.)

Python code to send message from discord.py Cog class:

```py
@commands.command
async def gimme_thumbs_up(self, ctx):
    await ctx.send('ok :thumbs_up:')
```

**Expected** (as seen in Discord web client):

![image](https://user-images.githubusercontent.com/7097256/131952712-546620de-64ef-4df2-8469-8ef59eccf073.png)

**Actual** (as seen in exported transcript):

![image](https://user-images.githubusercontent.com/7097256/131952908-5a762973-a1b7-435e-954a-d87169a2c54d.png)

**Comment by mahtoid** [comment]
> the web client might be pre-processing the message to replace the emoji on the client side before it's sent
It's exactly that. Any bot will read the text as `:thumbsup:` rather than an actual emoji which the client outputs. 

I could potentially look at utilising the `emoji` package more to convert the shortcode to emojis (and then convert for pwetty twemoji) but that is not something currently on the agenda. 

I'll happily add this to my idea-catalog and get around to it when I can.

Thank you for the report though💜
