### ISSUE TITLE
Feature Request: Embed threads in channel export

### ISSUE THREAD

**Issue by IIHERO4** [mahtoid/DiscordChatExporterPy#41]
idk maybe export threads within channel msgs

**Comment by mahtoid** [comment]
Hello @IIHERO4 

The way threads are set up currently, the bot would have to be added in to the thread for it to be able to view and export the thread content. `chat-exporter` should be able to handle exporting `threads` by themselves, however - to do this alongside a channel may be a little tricky due to the way they were designed by Discord. 

I will close this feature request due to the Discord design, but I will keep an eye for if they make any future changes to how threads operate within channels.
