### ISSUE TITLE
Attachments getting deleted after the original channel is deleted.

### ISSUE THREAD

**Issue by krypton007** [mahtoid/DiscordChatExporterPy#49]
### DiscordChatExporterPy Version

2.2.2

### Discord Version

2.0

### Bug Description

So when I created a transcript it showed the attachments in that channel but after deleting the channel discord also deletes the attachments. Hence, the transcript shows just a broken image instead of an attachment.
ss of the transcript after the channel is deleted - https://i.imgur.com/jRiXWpk.png
ss of another transcript when the channel is not deleted - https://i.imgur.com/1rWPOfW.png

There should be an option if someone wants to save raw bytes of attachments in transcript instead of attachment urls.

### Bug Traceback

None

### Additional Information

None

**Comment by mahtoid** [comment]
Hello @krypton007, thank you for the report.

As you were kind of aiming towards, the attachments disappear once the channel is deleted as the attachments are removed from Discords CDN servers.

To circumvent this issue, it would require downloading the attachments along with the transcript - so that when you view it, you could view the attachments too. However, for many reasons - along with being in the grey-area of Discord Developers TOS, this isn't something which will be introduced within this library. 

I do apologise, but thank you again for submitting an issue. If you find anything else, don't hesitate to open up another issue. 💜
