### ISSUE TITLE
Passing check for exporting.

### ISSUE THREAD

**Issue by ahdbarjoud** [mahtoid/DiscordChatExporterPy#8]
Allow export() to accept a check function the same way channel.purge() accepts it.

I know I can just pass the check function to purge and it would only return the messages that got deleted. But for uses other than exporting deleted messages where I want to have checks on what messages are extracted.

**Comment by mahtoid** [comment]
Hello @ahdbarjoud 

I'm struggling to understand what you're saying to do, to see what feature you're requesting.

How I'm reading it, is that you're wanting a "check" to grab certain messages, rather than just all of them? You can do this yourself and use `raw_export`. You can store all the messages you want in to a list, then pass it in to `chat_exporter.raw_export(CHANNEL, MESSAGES, TIMEZONE: Optional)`

Replacing:
CHANNEL for the channel you would want the transcript to be posted too,
MESSAGES for the list of messages you created with your check,
TIMEZONE to what timezone you'd like (you don't have to place this argument, default is Europe/London)

---

You can see an example in the README about how to call this function and produce a transcript from its return.

Does that solve your query, or do you still have a feature request?

**Comment by ahdbarjoud** [comment]
That does solve my problem. Thank you.
